import { IHalLinks } from '../types/IHalLinks'

/**
 * Contains configuration for React components for which search tags should be used to render data
 * on the event pages.
 */

// Tab content for related objects
export const relatedEntites: IHalLinks = {
  objects: {
    title: 'Objects in Exhibition',
    halLinkName: 'lux:eventIncludedItems',
    tab: 'objects',
  },
  works: {
    title: 'Works About or Related To',
    halLinkName: 'lux:eventWorksAbout',
    tab: 'works',
  },
  worksGeneratedBy: {
    title: 'Works Generated By',
    halLinkName: 'lux:eventCausedWorks',
    tab: 'works',
  },
  collectionsCausedBy: {
    title: 'Collections Caused By',
    halLinkName: 'lux:setCausedByEvent',
    tab: 'collections',
  },
  collectionsAboutEvent: {
    title: 'Collections About',
    halLinkName: 'lux:setAboutEvent',
    tab: 'collections',
  },
}

// Used for rendering related types accordions
export const relatedTypes: IHalLinks = {
  itemTypes: {
    title: 'Object Types',
    halLinkName: 'lux:eventObjectTypesUsed',
    tab: 'objects',
    jsonSearchTerm: 'classification',
  },
  itemTypesPeriods: {
    title: 'Object Types',
    halLinkName: 'lux:eventObjectTypesAbout',
    tab: 'objects',
    jsonSearchTerm: 'classification',
  },
  workTypes: {
    title: 'Work Types',
    halLinkName: 'lux:eventWorkTypesUsed',
    tab: 'works',
    jsonSearchTerm: 'classification',
  },
  workTypesPeriods: {
    title: 'Work Types',
    halLinkName: 'lux:eventWorkTypesAbout',
    tab: 'works',
    jsonSearchTerm: 'classification',
  },
  collectionTypes: {
    title: 'Collection Types',
    halLinkName: 'lux:eventSetTypes',
    tab: 'collections',
    jsonSearchTerm: 'classification',
  },
}

// Shows related accordions
export const relatedAccordions: IHalLinks = {
  conceptInfluenced: {
    title: 'Concepts Influenced',
    halLinkName: 'lux:eventConceptsInfluencedBy',
    tab: 'concepts',
  },
  agents: {
    title: 'Related People and Groups',
    halLinkName: 'lux:eventRelatedAgents',
    tab: 'people',
  },
  places: {
    title: 'Related Locations',
    halLinkName: 'lux:eventRelatedPlaces',
    tab: 'places',
  },
  materials: {
    title: 'Related Materials',
    halLinkName: 'lux:eventItemMaterials',
    tab: 'concepts',
    jsonSearchTerm: 'material',
  },
  subjects: {
    title: 'Related Concepts',
    halLinkName: 'lux:eventRelatedConcepts',
    tab: 'concepts',
  },
  ...relatedTypes,
}

// Used for rendering timelines
export const timelines: IHalLinks = {
  // Objects in Exhibition
  'lux:eventItemIncludedTime': {
    halLinkName: 'lux:eventItemIncludedTime',
    tab: 'objects',
  },
  // Works About or Related To
  'lux:eventWorksAboutTime': {
    halLinkName: 'lux:eventWorksAboutTime',
    tab: 'works',
  },
  // Works Generated By
  'lux:eventWorksCausedByTime': {
    halLinkName: 'lux:eventWorksCausedByTime',
    tab: 'works',
  },
  // Collections Created By
  'lux:eventSetsCausedByTime': {
    halLinkName: 'lux:eventSetsCausedByTime',
    tab: 'collections',
  },
  // Collections About
  'lux:eventSetsAboutTime': {
    halLinkName: 'lux:eventSetsAboutTime',
    tab: 'collections',
  },
}
