export const halLinkMapToLegendName: Map<string, string> = new Map([
  // Agent Search Tags
  ['lux:agentItemMadeTime', 'Objects Produced'],
  ['lux:agentItemEncounteredTime', 'Objects Encountered'],
  ['lux:agentWorkCreatedTime', 'Works Created'],
  ['lux:agentWorkPublishedTime', 'Works Published'],
  ['lux:agentSetAboutTime', 'Collections About'],
  ['lux:agentSetCreatedTime', 'Collections Created'],
  ['lux:agentSetPublishedTime', 'Collections Published'],

  // Concept Search Tags
  ['lux:conceptItemMadeTime', 'Objects Produced'],
  ['lux:conceptItemEncounteredTime', 'Objects Encountered'],
  ['lux:conceptWorkCreatedTime', 'Works Created'],
  ['lux:conceptWorkPublishedTime', 'Works Published'],

  // Event Search Tags
  ['lux:eventItemIncludedTime', 'Objects in Exhibition'],
  ['lux:eventWorksAboutTime', 'Works About or Related To'],
  ['lux:eventWorksCausedByTime', 'Works Generated By'],
  ['lux:eventSetsCausedByTime', 'Collections Caused By'],
  ['lux:eventSetsAboutTime', 'Collections About'],

  // Place Search Tags
  ['lux:placeItemMadeTime', 'Objects Produced'],
  ['lux:placeItemEncounteredTime', 'Objects Encountered'],
  ['lux:placeWorkCreatedTime', 'Works Created'],
  ['lux:placeWorkPublishedTime', 'Works Published'],
  ['lux:placeWorkAboutTime', 'Works About or Related To'],
  ['lux:placeSetAboutTime', 'Collections About'],
])
