export const facetNameMap: Map<string, string> = new Map([
  ['itemProductionDate', 'Objects Produced'],
  ['itemEncounteredDate', 'Objects Encountered'],
  ['itemIncludedDate', 'Objects in Exhibition'],
  ['workGeneratedBy', 'Works Generated By'],
  ['workCreationDate', 'Works Created'],
  ['workPublicationDate', 'Works Published'],
  ['workCreationOrPublicationDate', 'Works About'],
  ['setAboutDate', 'Collections About'],
  ['setCausedByDate', 'Collections Caused By'],
  ['setCreationDate', 'Collections Created'],
  ['setPublicationDate', 'Collections Published'],
])
