import React from 'react'
import { Popover, OverlayTrigger } from 'react-bootstrap'

import { StyledButton } from './LuxOverlay'

const RtiPopover: React.FC = () => {
  const [isOpen, setIsOpen] = React.useState(false)

  const getButtonText = (): string =>
    isOpen ? 'Hide RTI info' : 'Learn more about RTI images'

  const popover = (
    <Popover
      id="popover-basic"
      style={{ maxWidth: '300px' }}
      title="RTI image popover"
    >
      <Popover.Header as="h3">About RTI Images</Popover.Header>
      <Popover.Body>
        <p className="mt-2 mb-0">
          This is some really cool information about RTI images generated by
          Copilot. You can learn more about how to view and use them in our
          collection.
        </p>
      </Popover.Body>
    </Popover>
  )
  return (
    <OverlayTrigger
      placement="bottom"
      trigger={['click']}
      overlay={popover}
      onToggle={(show) => setIsOpen(show)}
    >
      <StyledButton
        variant="info"
        className="p-0"
        data-testid="tooltip-button"
        style={{ border: 'none', background: 'none' }}
      >
        <i
          className="bi bi-question-circle"
          style={{
            fontSize: '1rem',
            marginRight: '0.2rem',
          }}
          data-testid="tooltip-icon"
        />
        {getButtonText()}
      </StyledButton>
    </OverlayTrigger>
  )
}

export default RtiPopover
